export const GET_PRODUCT = 'GET_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const UPDATE_LINK_IMAGE_PRODUCT = 'UPDATE_LINK_IMAGE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_IMAGE_PRODUCT = 'DELETE_IMAGE_PRODUCT';
