import {StyleSheet} from 'react-native';
import Colors from '@const/Colors';
import {responsiveHeight, responsiveWidth} from '@utils/DimenUtils';
import Fonts from '@const/Fonts';
const styles = StyleSheet.create({
  viewProduct: {
    backgroundColor: Colors.white,
    flexDirection: 'column',
    paddingHorizontal: responsiveWidth(15),
    paddingVertical: responsiveHeight(15),
  },
  txtTitleProduct: {
    color: Colors.txtDark,
    fontFamily: Fonts.type.medium,
    fontSize: Fonts.size.text,
    fontWeight: 'bold',
  },
  viewItemProduct: {
    paddingBottom: responsiveHeight(8),
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: responsiveHeight(20),
    borderBottomWidth: 1,
    borderBottomColor: Colors.line,
  },
  viewMainImage: {
    marginRight: responsiveWidth(20),
  },
  viewImage: {
    width: responsiveHeight(60),
    height: responsiveHeight(60),
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.line,
  },
  image: {
    width: responsiveHeight(60),
    height: responsiveHeight(60),
    borderRadius: 8,
    resizeMode: 'stretch',
  },
  viewLoading: {
    position: 'absolute',
    top: responsiveHeight(20),
    left: responsiveHeight(20),
  },
  viewNumberProduct1: {
    backgroundColor: Colors.white,
    position: 'absolute',
    top: -responsiveHeight(11),
    right: -responsiveHeight(11),
    width: responsiveHeight(22),
    height: responsiveHeight(22),
    borderRadius: responsiveHeight(11),
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.lightGreen,
  },
  viewNumberProduct2: {
    backgroundColor: Colors.white,
    position: 'absolute',
    top: -responsiveHeight(13),
    right: -responsiveHeight(13),
    width: responsiveHeight(26),
    height: responsiveHeight(26),
    borderRadius: responsiveHeight(13),
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.lightGreen,
  },
  viewNumberProduct3: {
    backgroundColor: Colors.white,
    position: 'absolute',
    top: -responsiveHeight(15),
    right: -responsiveHeight(15),
    width: responsiveHeight(30),
    height: responsiveHeight(30),
    borderRadius: responsiveHeight(15),
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.lightGreen,
  },
  viewNumberProduct4: {
    backgroundColor: Colors.white,
    position: 'absolute',
    top: -responsiveHeight(17),
    right: -responsiveHeight(17),
    width: responsiveHeight(34),
    height: responsiveHeight(34),
    borderRadius: responsiveHeight(17),
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.lightGreen,
  },
  txtNumberProduct: {
    color: Colors.lightGreen,
    fontFamily: Fonts.type.medium,
    fontSize: Fonts.size.text,
    fontWeight: 'bold',
  },
  viewContentProduct: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-around',
  },
  viewNameAndPriceProduct: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  txtNameProduct: {
    color: Colors.txtDark,
    fontFamily: Fonts.type.medium,
    fontSize: Fonts.size.text,
    fontWeight: 'normal',
  },
  txtProduct: {
    color: Colors.gray,
    fontFamily: Fonts.type.medium,
    fontSize: Fonts.size.medium,
    fontWeight: 'normal',
  },
});
export default styles;
